server:
  port: 8081

spring:
  application:
    name: business-service
  rsocket:
    server:
      transport: ${SPRING_RSOCKET_SERVER_TRANSPORT:tcp}
      port: ${SPRING_RSOCKET_SERVER_PORT:7000}

business:
  processing-time-ms: ${BUSINESS_PROCESSING_TIME:250}
  max-in-flight: ${BUSINESS_MAX_IN_FLIGHT:32}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
